"""create empty  tables

Revision ID: a9f023997a60
Revises: 0773e30bb7ac
Create Date: 2023-12-16 04:19:14.961312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f023997a60'
down_revision = '0773e30bb7ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
