"""create reverted  tables

Revision ID: adc3894c7740
Revises: a9f023997a60
Create Date: 2023-12-16 04:20:28.305635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc3894c7740'
down_revision = 'a9f023997a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
